### ISSUE TITLE
platform/plugin build order?

### ISSUE THREAD

**Issue by LukeHartcher** [Microsoft/TACO#281]
I am using a plugin that requires the platform to be added prior to the plugins.

https://github.com/nordnet/cordova-universal-links-plugin/issues/54

Is it possible to set TACO on iOS to add the platforms first, before the plugins?

**Comment by MSLaguana** [comment]
We don't support that at the moment, but you can work around it by submiting multiple builds:

1. First make sure that any order-dependent plugins are not added to your project
2. Build your project
3. Add the order-dependent plugins
4. Build the project again

Note that if you do a clean build, or if the build server forgets about your project due to getting other build requests, you will need to repeat these steps.

**Comment by LukeHartcher** [comment]
Thanks. Do I need incremental build turned on for this?

**Comment by MSLaguana** [comment]
Yes, this would make use of the incremental build functionality. I don't believe that you need to "turn it on" though, it should be automatically enabled, and building without doing a clean build should re-use the project across builds. That's what lets it add the platform on the first invocation, and then add the plugins on the second invocation.

**Comment by LukeHartcher** [comment]
Cool. Can you tell me how the actual build order is determined i.e is it always plugins before platform or vice-versa? And does the order in which they are listed in config.xml have any impact?

**Comment by MSLaguana** [comment]
When you build iOS remotely, it ends up being built using this code here: https://github.com/Microsoft/TACO/blob/master/src/taco-remote-lib/common/builder.ts#L72

The sequence is currently

1. Add/remove plugins,
2. Add platform if this is the first build and not an incremental build, or if the platform has changed since the previous build
3. cordova prepare
4. cordova compile

We are currently in the process of replacing steps 3 and 4 with just "cordova build", which internally calls prepare and compile.

The way that we deal with plugins is a little complicated since we want to support all plugins and not just those which are publicly available. If you have run "cordova platform add" on your local machine so the plugins/<plugin> folder exists, then when you build remotely we send over the contents of the plugins folder, and we explicitly add that to the project in the first stage. We don't attempt to enforce an order on the addition of plugins.

If your config.xml specifies plugins, we do _not_ add them at this point. These plugins will be added by cordova when we end up running cordova prepare, and it will use whatever behavior cordova does so I'm not sure if there are guarantees about ordering there.

**Comment by hamiltonia** [comment]
Closing as a work around exists and there is no current plan to change this behavior.
