### ISSUE TITLE
Remote Build IOS second build fails looking for Android?

### ISSUE THREAD

**Issue by itbeyond** [Microsoft/TACO#299]
I am building on VS 2015 output to local Mac using remote-build. It works perfectly for the first build (debug or release) then every time I go to submit a build again (second time in one session). I get this crash stating that the build is looking for Android?  This just started happening today, I have rebooted the mac and my work station, removed the IOS platform and readded error is still the same. If I reboot VS2015 project it works great the first time.

1>------ Build started: Project: EONav, Configuration: Debug iOS ------
1>Build started 27/05/2016 10:14:06 PM.
1>     1>
1>InstallMDA:
1>         Your environment has been set up for using Node.js 4.4.4 (x64) and npm.
1>         ------ Ensuring correct global installation of package from source package directory: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\ApacheCordovaTools\packages\vs-tac
1>         ------ Name from source package.json: vs-tac
1>         ------ Version from source package.json: 1.0.42
1>         ------ Package already installed globally at correct version.
1>       BuildMDA:
1>         ------ Cordova tools 6.1.1 already installed.
1>         ------ Build Settings:
1>         ------ Build Settings:
1>         ------    platformConfigurationBldDir: C:\VS Projects\Cordova\EONav\bld\iOS\Debug
1>         ------    platformConfigurationBinDir: C:\VS Projects\Cordova\EONav\bin\iOS\Debug
1>         ------    buildCommand: build
1>         ------    platform: iOS
1>         ------    cordovaPlatform: ios
1>         ------    configuration: Debug
1>         ------    cordovaConfiguration: Debug
1>         ------    projectName: EONav
1>         ------    projectSourceDir: C:\VS Projects\Cordova\EONav
1>         ------    npmInstallDir: C:\Users\david.ITBEYOND\AppData\Roaming\npm
1>         ------    buildServerUrl: https://Davids-Mac.office.itbeyond.com.au:3000/cordova
1>         ------    buildTarget: iOSLocalDevice
1>         ------    language: en-US
1>         ------ Platform ios already exists
1>         ------ Updating plugins
1>         ------ Currently installed plugins: cc.fovea.cordova.purchase@6.0.0,com.transistorsoft.cordova.background-geolocation@1.6.1,cordova-plugin-background-fetch@3.0.4,cordova-plugin-camera@2.2.0,cordova-plugin-compat@1.0.0,cordova-plugin-console@1.0.3,cordova-plugin-crosswalk-webview@1.7.0,cordova-plugin-device@1.1.2,cordova-plugin-dialogs@1.2.0,cordova-plugin-file@4.2.0,cordova-plugin-file-transfer@1.5.1,cordova-plugin-geolocation@2.2.0,cordova-plugin-image-picker@1.0.8,cordova-plugin-inappbrowser@1.4.0,cordova-plugin-insomnia@4.2.0,cordova-plugin-ios-itbeyond-export-compliance@0.0.1,cordova-plugin-network-information@1.2.1,cordova-plugin-splashscreen@3.2.2,cordova-plugin-statusbar@2.1.3,cordova-plugin-whitelist@1.2.2,cordova-plugin-zip@3.1.0,cordova-sqlite-evfree@0.8.2,ionic-plugin-keyboard@1.0.8,sqli-cordova-disk-space-plugin@1.0.0
1>         ------ Currently installed dependent plugins: cordova-plugin-dialogs,cordova-plugin-background-fetch,cordova-plugin-compat,cordova-plugin-file
1>         ------ Currently configured plugins:
1>         ------ Incremental Build: true
1>         ------ Submitting new build request to: https://Davids-Mac.office.itbeyond.com.au:3000/cordova/build/tasks?command=build&vcordova=6.1.1&cfg=debug&options=--device&buildNumber=490&loglevel=info
1>         ------ New Build information: {"command":"build","vcordova":"6.1.1","cfg":"debug","options":"--device","buildNumber":"490","loglevel":"info","status":"Uploaded","buildCommand":"build","buildPlatform":"ios","configuration":"debug","buildLang":"en-US","buildDir":"/Users/david/.taco_home/remote-builds/taco-remote/builds/490","logLevel":0,"previousvcordova":"6.1.1","submissionTime":"2016-05-27T14:14:45.896Z","changeList":null,"buildSuccessful":false,"messageArgs":null,"message":"Uploaded build request payload.","tgzFilePath":"/Users/david/.taco_home/remote-builds/taco-remote/builds/490/upload_490.tgz","appDir":"/Users/david/.taco_home/remote-builds/taco-remote/builds/490/cordovaApp","statusTime":"2016-05-27T14:15:00.106Z"}
1>         ------ 10:14:45 PM Checking on build status from https://davids-mac.office.itbeyond.com.au:3000/cordova/build/tasks/490 [Attempt 1]
1>         uploaded - Uploaded build request payload.
1>         ------ 10:14:50 PM Checking on build status from https://davids-mac.office.itbeyond.com.au:3000/cordova/build/tasks/490 [Attempt 2]
1>         uploaded - Uploaded build request payload.
1>         ------ 10:14:55 PM Checking on build status from https://davids-mac.office.itbeyond.com.au:3000/cordova/build/tasks/490 [Attempt 3]
1>         error - Build failed with error The provided path "/Users/david/.taco_home/remote-builds/taco-remote/builds/490/cordovaApp/platforms/android" is not an Android project.
1>         ------ Remote build log follows
1>         Executing "before_plugin_add"  hook for all plugins.
1>         Resolving module name for q => q
1>         find: platforms/android/cordova: No such file or directory
1>
1>         No version specified, retrieving version from config.xml
1>         No version given in config.xml, attempting to use plugin engine info
1>         No plugin engine info found or not using registry, falling back to latest version
1>         Calling plugman.fetch on plugin "cordova-plugin-vs-taco-support"
1>         Calling plugman.install on plugin "/Users/david/.taco_home/remote-builds/taco-remote/builds/490/cordovaApp/plugins/cordova-plugin-vs-taco-support" for platform "android
1>         Installing "cordova-plugin-vs-taco-support" for android
1>         Executing "before_plugin_install"  hook for "cordova-plugin-vs-taco-support" on android.
1>         Install start for "cordova-plugin-vs-taco-support" on android.
1>          Using this version of Cordova with older version of cordova-android is being deprecated. Consider upgrading to cordova-android@5.0.0 or newer.
1>         Failed to install 'cordova-plugin-vs-taco-support':CordovaError The provided path "/Users/david/.taco_home/remote-builds/taco-remote/builds/490/cordovaApp/platforms/android" is not an Android project.
1>             at new android_parser (/Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/cordova-lib/src/cordova/metadata/android_parser.js:35:15)
1>             at new PlatformApiPoly (/Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:63:20)
1>             at Object.getPlatformApi (/Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:65:23)
1>             at handleInstall (/Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:604:29)
1>             at /Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:403:28
1>             at _fulfilled (/Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/q/q.js:787:54)
1>             at self.promiseDispatch.done (/Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/q/q.js:816:30)
1>             at Promise.promise.promiseDispatch (/Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/q/q.js:749:13)
1>             at /Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/q/q.js:509:49
1>             at flush (/Users/david/.taco_home/node_modules/cordova/6.1.1/node_modules/cordova/node_modules/q/q.js:108:17)
1>         Failed to build app for buildNumber 490: The provided path "/Users/david/.taco_home/remote-builds/taco-remote/builds/490/cordovaApp/platforms/android" is not an Android project.
1>     1>
1>MSBUILD : cordova-build error : Error: Remote build error from the build server Build failed with error The provided path "/Users/david/.taco_home/remote-builds/taco-remote/builds/490/cordovaApp/platforms/android" is not an Android project. - 1
1>         Error Remote build error from the build server Build failed with error The provided path "/Users/david/.taco_home/remote-builds/taco-remote/builds/490/cordovaApp/platforms/android" is not an Android project. - {1}
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:50.48
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by MSLaguana** [comment]
You say that if you restart remotebuild / the mac, but keep VS open before re-submitting a build, the build fails complaining about android, but if you keep remotebuild running and restart VS then it succeeds, is that correct?

What happens if you try to build -> Rebuild Solution for iOS?

Does your config.xml include any `<engine [...] />` tags, in particular ones that refer to android? And have you added/built the android platform locally on your windows machine?

**Comment by itbeyond** [comment]
@MSLaguana Yes is I restart VS2015 and nothing else I can correctly build/debug for IOS.

If I use Build -> Rebuild it seems to work. Fails when I use the green arrow in the toolbox to deploy to devices.

Yes I build Android/IOS on this system all the time switching from one to the other bewteen builds.

**Comment by MSLaguana** [comment]
Could you please upload a build log of a successful / first run? I tried replicating your build, but you have a few plugins which I don't have access to, and I suspect that the failure may be due to some plugin interactions.

Could you also please look on your build machine in `~/.taco_home/remotebuild/taco-remote/builds/<build number>/cordovaApp/` and tell me what files are present in the `platforms` and `plugins` folders after a successful build?

**Comment by itbeyond** [comment]
Attached is a build from the first successful build.
[build.zip](https://github.com/Microsoft/TACO/files/290243/build.zip)

In platforms there is an Android folder, IOS folder and platforms.json file.
In the Android folder there is one path platforms\android\assets\www\js with a js file from my system. This file is a scripted minified output that comes from one of my before_build hooks. I suspect this may be causing the problem however it should not be. The script I have added in config.xml hooks is this:

```
module.exports = function(context) {
    var Q = context.requireCordovaModule('q');
    var deferral = new Q.defer();

    var path = require('path'),
        gulp = require('gulp'),
        gulpfile = path.join(__dirname, '..', 'gulpfile.js');

        require(gulpfile);
        console.log(context);
        if (context.cmdLine.indexOf('Release') > 0 || context.opts.options.release) {
            gulp.start('build-traveller-release.js').once('task_stop', function () {
                console.log('build-traveller-release.js done');
                deferral.resolve();
            });
        } else {
            gulp.start('build-traveller.js').once('task_stop', function () {
                console.log('build-traveller.js done');
                deferral.resolve();
            });
        }

    return deferral.promise;
}
```


The running gulp task is this for release (but the both do the same just one has stripDebug() for removal of console.log commands.

```
gulp.task("build-traveller-release.js", function () {
    return gulp.src(['www/js/app.js', 'www/js/*/*.js'])
   .pipe(concat('traveller.js'))
   .pipe(stripDebug())
   .pipe(ngannotate())
   .pipe(uglify())
   .pipe(gulp.dest('www/js'))
   .pipe(gulp.dest('platforms/ios/www/js'))
   .pipe(gulp.dest('platforms/android/assets/www/js'));
})
```
So the script will force write out the ios and android paths. This however should not cause the IOS builder to try to run and IOS build but I suspect this could be where the problem is.

**Comment by MSLaguana** [comment]
I do believe it is that `platforms/android/*` file which is causing an issue. When we perform a build, we `cordova plugin add cordova-plugin-vs-taco-support` to add in some hooks, but after the first build your hooks have created the `platforms/android` folder which makes cordova think that there is an android platform present and thus it should install the `cordova-plugin-vs-taco-support` plugin for android. This fails because it is not a real android platform.

You can replicate this failure by creating a cordova project, adding an empty `platforms/android` folder and trying to `cordova plugin add cordova-plugin-device` for example.

To fix this, ideally I think you should modify your build hook to not modify assets for platforms that are not present. I could modify taco-remote-lib to only install the cordova-plugin-vs-taco-support plugin on the first run, but you would run into this same issue the next time you added a new plugin to your project.

**Comment by MSLaguana** [comment]
In fact, I believe that if you make your build hook a before_prepare task (before_build should work as well, but before_prepare is more specific) then if you just write to `www/js`, then the `cordova prepare` implicit in building will copy the result from `www` to the appropriate location in each of the platforms.

**Comment by itbeyond** [comment]
I did try the www/js only write in the before_build and I was constantly one version behind when it went out to the bin folder. This is why I went out to all three to ensure that the build would be the right version. I will give before_prepare a go and see what happens.

**Comment by MSLaguana** [comment]
I see that you are using the undocumented `gulp.start` to trigger your gulp tasks. I would suggest that rather than listening to `task_stop` events, you should pass a callback to it; one reason that things may have been failing for you could be if you have multiple gulp tasks running at once, and so a `task_stop` event for a different task may have triggered your event handler and caused you to resolve the promise early.

**Comment by itbeyond** [comment]
Is there any documented procedure to use for this type of task execution? It seems strange that VS talks about using gulp via the task runner but not how to link task runner tasks to the hooks functions or where the two should be used. If you look at the docs it is very confusing as TACO docs start talking about using gulp for the whole build process and not how to use it in Cordova hooks.

**Comment by MSLaguana** [comment]
The most supported way of using gulp is via the command line, and that is how VS interacts with gulpfiles. In a lot of cases where you want to manually invoke some task, it's much simpler to split the functionality out into a normal function, and have both the gulpfile and your other code invoke the function rather than having everything try to invoke the gulp task. This breaks down when you have dependencies between tasks; I think that there is a `run-sequence` package which tries to deal with that case.

If you do go with moving things to plain functions, then you can convert the `gulp.src().[...]` stream to a promise by listening for the stream's `'end'` event I believe (And also listen for `'error'` in case something goes wrong). We do that at https://github.com/Microsoft/TACO/blob/master/tools/GulpUtils.ts#L155
