### ISSUE TITLE
Visual Studio 2015 time out when starting debugger for iOS

### ISSUE THREAD

**Issue by Rainson12** [Microsoft/TACO#315]
Hey guys,
I'm having an issue where as Visual Studio 2015 is not capable of using the iOS simulator from a mac os. The building works fine but as starting up the app in the ios simulator on the mac takes more than 20 seconds, Visual Studio breaks up the attaching debugger proccess. The error is 
`Timed out launching the app. Check your network connection to the mac and try again. If you are launching to a device, make sure you have Web Inspector enabled on it.`

The app does lunch properly it just takes 2-3 seconds longer than VS can wait. Is there any way to increase the timeout limit? I already changed the limits in the remotebuild.config
to 

`"appLaunchStepTimeout“ : 60000,
"emulatorLaunchTimeout": 60000,`
even changing it to like 3 or 5 minutes doesnt make a diffrence, VS cancels after about 20 seconds.

**Comment by MSLaguana** [comment]
The time that VS waits for the emulator is specified in VS itself, and there is no option in VS 2015. Visual Studio 2017 RC is now available which has a fix for this, so you could try using that, otherwise if you ensure that the emulator is already started before you launch your build (Or you launch a second time) The emulator should be warmed up and not take as long.

If you encounter further issues, please report them at https://github.com/microsoft/remotebuild since this repo has been deprecated.
